# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracking.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tracking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etracking.proto\x12\tfasttrack\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\x14\x44riverLocationUpdate\x12\x13\n\x0b\x64river_uuid\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12!\n\x06status\x18\x04 \x01(\x0e\x32\x11.fasttrack.Status\"\x05\n\x03\x41\x63k\"G\n\nAreaFilter\x12\x12\n\ncenter_lat\x18\x01 \x01(\x01\x12\x12\n\ncenter_lng\x18\x02 \x01(\x01\x12\x11\n\tradius_km\x18\x03 \x01(\x01\"V\n\nDriverInfo\x12\x13\n\x0b\x64river_uuid\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x12!\n\x06status\x18\x03 \x01(\x0e\x32\x11.fasttrack.Status\"!\n\nGeoRequest\x12\x13\n\x0b\x64river_uuid\x18\x01 \x01(\t\"\x9d\x01\n\x0e\x44riverLocation\x12\x13\n\x0b\x64river_uuid\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12!\n\x06status\x18\x04 \x01(\x0e\x32\x11.fasttrack.Status\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*Z\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x14\n\x10STATUS_AVAILABLE\x10\x01\x12\x12\n\x0eSTATUS_ON_TRIP\x10\x02\x12\x12\n\x0eSTATUS_OFFLINE\x10\x03\x32\xf5\x01\n\x0fTrackingService\x12M\n\x14UpdateDriverLocation\x12\x1f.fasttrack.DriverLocationUpdate\x1a\x0e.fasttrack.Ack\"\x00(\x01\x30\x01\x12\x45\n\x13GetAvailableDrivers\x12\x15.fasttrack.AreaFilter\x1a\x15.fasttrack.DriverInfo0\x01\x12L\n\x14StreamDriverLocation\x12\x15.fasttrack.GeoRequest\x1a\x19.fasttrack.DriverLocation\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=542
  _globals['_STATUS']._serialized_end=632
  _globals['_DRIVERLOCATIONUPDATE']._serialized_start=62
  _globals['_DRIVERLOCATIONUPDATE']._serialized_end=177
  _globals['_ACK']._serialized_start=179
  _globals['_ACK']._serialized_end=184
  _globals['_AREAFILTER']._serialized_start=186
  _globals['_AREAFILTER']._serialized_end=257
  _globals['_DRIVERINFO']._serialized_start=259
  _globals['_DRIVERINFO']._serialized_end=345
  _globals['_GEOREQUEST']._serialized_start=347
  _globals['_GEOREQUEST']._serialized_end=380
  _globals['_DRIVERLOCATION']._serialized_start=383
  _globals['_DRIVERLOCATION']._serialized_end=540
  _globals['_TRACKINGSERVICE']._serialized_start=635
  _globals['_TRACKINGSERVICE']._serialized_end=880
# @@protoc_insertion_point(module_scope)
